### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by zdolny** [nescomtm/zad_85#1]
- [ ] dodaj .gitignore z ignorowaniem node_modules
- [ ] popraw wciecia w html (linie 17, 20, 22)
- [ ] tego tak naprawde nie musisz tutaj pisac, bo to domyslne zachowanie robota google'a dla stron `<meta name="robots" content="index,follow" />`

**Comment by nescomtm** [comment]
.gitignore mam w katalogu z zdaniem 8.5 ???
wciecia zrobione
robicik usunięty

**Comment by nescomtm** [comment]
plik index.html jest tworzony i zapisany w jako UTF-8 a potem po ponownej edycji jest UTF8+BOm
i nie mogę tego rozkminić, mimo ustawionego w konfiguracji edytora UTF-8 

jutro będę z tym waczył

**Comment by nescomtm** [comment]
Miłego Week Endu

**Comment by zdolny** [comment]
dorzucilem zmiane kodowania na utf-8
